[package]
name = "siunits"
version = "0.1.0"
authors = ["Marvin Gazibarić <m.gazibaric@live.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
